- api/BuildApi.ts
- api/CoreApi.ts
- api/FileContainerApi.ts
- api/GalleryApi.ts
- api/GitApi.ts
- api/RestClient.ts
- api/TaskAgentApi.ts
- api/TaskApi.ts
- api/TestApi.ts
- api/TfvcApi.ts
- api/WorkItemTrackingApi.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- api/interfaces/common/VsoBaseInterfaces.ts
- package.json
The methods in RestClient.ts that handled JsonWrappedArrays are no longer necessary because the generator will use VSSJsonCollectionWrappers whenever the controllers do. They actually caused problems in the generator logic because sometimes arrays that are taken as body parameters or returned are NOT wrapped up in that {count:number, value:T} form. This caused a 400, for example, on the previous version of the generated TestApi.addTestResultsToTestRun method.
Also updated the clients to the newest version in VSO.
Bumped version to 0.4.0
> 0.4.0: removed array wrapping (covered by VSSJson) and updated clients

- api/WorkItemTrackingApi.ts
* Added project parameter to the createWorkItem method
* Added project, and type to routeValues
> Fix for createWorkItem

- LICENSE
- ThirdPartyNotices.txt
- api/HttpClient.ts
- api/WebApi.ts
- api/handlers/apiversion.ts
- api/handlers/basiccreds.ts
- api/handlers/bearertoken.ts
- api/handlers/ntlm.ts
- api/interfaces/common/VsoBaseInterfaces.ts
- api/opensource/node-http-ntlm/ntlm.js
- api/opensource/node-http-ntlm/readme.txt
- gulpfile.js
- node/node.d.ts
- package.json
(Pending code scan of node-http-ntlm; already in progress.)
Add an NTLM handler using portions of the node-http-ntlm package.  Caller provides username and password (and optional domain and workstation) to create the handler.  Added two methods to IRequestHandler to determine if the handler can handle the particular type of authentication (e.g., NTLM).  I considered adding a new interface but it ended up making the code where the RequestHandler is used more complex (WebApi.ts) so I went the simpler route.
Updated node.d.ts with file from DefinitelyTyped (the ntlm support required the AgentOptions interface exposed by node).  Note that the version of Node.js (0.10.1) remains the same.
Took a dependency on underscore, received OSS approval and added ThirdPartyNotices.txt.
Updated Copyright …
> Add NTLM support

- api/handlers/ntlm.ts
- package.json
The proxy support in vsts-node-api v4+ prevents existing NTLM authentication from working properly.  For now, disable the proxy support in the NTLM auth handler.  (The proxy support will still be used for Team Services.)
> Disable proxy for NTLM authentication

- api/handlers/ntlm.ts
WebApi.ts new NtlmCredetialHandler initialization was wrong order at line39. workstation and domain order parameters are being set in reverse order.
Because it is exported in that order at WebApi.ts, I changed the constructor signature in ntlm.ts instead of changing WebApits
Fix #69
> WebApi.ts new NtlmCredetialHandler initialization was wrong order

- package.json
Fixes #169. When I removed Typings I removed the .d.ts reference for the main js file and didn't replace it with a types property referencing the same type definition file.
Also created #171 to install a as a packed module when running samples to catch issues like this in the future.
> Add types definition for main js file.

- samples/git.ts
- samples/samples.json
- samples/tsconfig.json
- samples/wiki.ts
Added samples for Git and Wiki. Probably could be developed more (in particular Git), but this is at least a good starting place.
> Add samples

- CONTRIBUTING.md
Received suggestion that it might be helpful to be more explicit about what files we're accepting PRs for (and it experientially, it probably would have helped me ramp up).
> Add detail to contribution doc

- samples/profile.ts
- samples/samples.json
- samples/tsconfig.json
> Added Profile Sample

- make.js
- package-lock.json
- package.json
- test/package-lock.json
- test/units/tests.ts
- test/units/tsconfig.json
Changes to package-locks are just from builds, probably should have been added in some previous commit.
> Stopping tests from automatically generating .js files

- api/WebApi.ts
- test/units/tests.ts
if the host of the TFS instance is listed in the $no_proxy variable do
not set options.proxy
Feature request #183
> support $no_proxy

- api/WebApi.ts
- make.js
- test/units/tests.ts
- test/units/tsconfig.json
Cloned/ran tests and they weren't working because of a missing tsconfig file. Added that, ran tests, and realized some were failing because isNoProxyHost fails when no_proxy isn't set. Finally, updated tests to automatically build the library first.
> Found issue when no proxy wasn't set and set up tests better

- api/VsoClient.ts
- test/units/tests.ts
> Use `toUTCString()` on Date objects.

- README.md
Also, use string interpolation in example. (Would it be appropriate to make this change throughout the samples, and to normalize string quoting at the same time?)
> Fix "TypeScript" casing in README

- README.md
- samples/build.ts
- samples/buildArtifact.ts
- samples/common.d.ts
- samples/common.ts
- samples/creation.ts
- samples/filecontainer.ts
- samples/git.ts
- samples/policy.ts
- samples/profile.ts
- samples/run.ts
- samples/task.ts
- samples/wiki.ts
- Normalize quote types to use double quotes everywhere. (The existing code was split almost 50/50 between single and double quotes and I couldn't find a style guide, so I choose the standard the TypeScript team uses. If you prefer single quotes, I'll just change it over to that.)
- Use template strings where possible instead of concatenating strings.
@damccorm: I finally got around to this. Could you have a look?
> Cleanup strings in samples

- api/WebApi.ts
- api/interfaces/common/VsoBaseInterfaces.ts
- package-lock.json
- package.json
> Enable retries

- api/WebApi.ts
- package-lock.json
- test/package-lock.json
This change makes it possible to include the library in a webpacked project. For browser calls, we use the browser's user agent, which should be fine.
> change how useragent is formulated to support use in browser

- samples/common.ts
- samples/profile.ts
Right now, profile samples are failing under our instructions. This is because when you try to hit `https://dev.azure.com/{orgName}/_apis/ResourceAreas` it fails, you have to hit `https://vssps.dev.azure.com/{orgName}/_apis/ResourceAreas` instead because it is considered a deployment level concept, not a project level concept. In general, things around profile don't seem settled so I took out some of the samples here as well (they were failing too).
Maybe we should add this back at some point, for now I think we should prioritize getting things working though.
Fixes #303
> Get profile samples working

- api/WebApi.ts
Currently, the check for isBrowser returns false in the browser due to the this===window part of the check. Instead use window.document (which is only available in the browser) to check for the browser.
> Fixed isBrowser check to use window.document instead

- package-lock.json
- package.json
fixes #331 The tunnel dependency is using an old version. The newer version includes a fix for the error.
> Fix tunnelling error when getting WebApi behind a proxy

- api/FileContainerApi.ts
Using this package with yarn v2 throws `Error: Couldn't find a suitable Node resolution for the specified unqualified path`.
Might be yarn v2 being too strict but the import isn't consistent with the others anyway so we might as well fix it here.
> Fix "Couldn't find a suitable Node resolution" in yarn v2

- api/WebApi.ts
- package-lock.json
- package.json
When people use webpack, the releative location of files gets moved around - this makes sure we don't fail on that since its only used for userAgents. I think we technically have that as telemetry, but I've never seen us use it
Fixes #312
> Dont fail on missing package.json

- README.md
This changes the sample to run from `http` (no longer an option) to
existing and working `projectAnalysis`
Thanks!
> Fix sample project snippet parameter

- api/WebApi.ts
- api/handlers/basiccreds.ts
- api/handlers/bearertoken.ts
- api/handlers/personalaccesstoken.ts
- package-lock.json
- package.json
Passed allowCrossOriginAuthentication to BasicCredentialHandler constructor of typed-rest-client.
Related issue: https://github.com/microsoft/azure-devops-node-api/issues/419
> Passed allowCrossOriginAuthentication to BasicCredentialHandler constructor - to fix authorization issue

- package-lock.json
- package.json
- test/package-lock.json
Fix CVE-2021-23358
Remove unused underscore dependency
> Bump dependencies (typed-rest-client)

- .github/workflows/stale.yml
v1 of the stale bot is malfunctioning, e.g. see how #411 was closed despite people commenting. Hopefully it's fixed in v3
> Update actions/stale to v3

- README.md
- package-lock.json
- package.json
This is causing some people's cred scanner to go off, we should just remove it since its just an example and doesn't serve too much purpose
> Remove fake credentials from readme

- samples/task.ts
- samples/workItemTracking.ts
Fix task and workItemTracking samples which are failing now.
`uploadSecureFile `requires Content-Length to be specified in the headers.
`getWorkItemTypeColors` requires projectNames instead of ids
> Fix samples

- api/VsoClient.ts
- package-lock.json
- package.json
- test/package-lock.json
Updated the validation of values in query parameters. If values 'false' or '0' are passed in the query parameters, they are simply skipped, as in the case of undefined value.
Tested changes manually.
Related issue: https://github.com/microsoft/azure-devops-node-api/issues/487
> Update the validation of values in query parameters

- azure-pipelines.yml
- test/package-lock.json
- test/package.json
- test/units/tests.ts
Update the library to check compatibility with Node 16
- Added Node 16 to pipeline
- Fixed test for using in Node 16
- Changes have been tested on Linux, Windows, macOS by unit-tests
- Library has been tested manually as part of some task with Node 16 runtime. Used tasks and cases are described [here](https://github.com/microsoft/azure-devops-node-api/pull/509#issuecomment-1185260049)
- Enough test coverage for changes and current test coverage for the task doesn't look poor
- I didn't find any breaking changes
- There are no other concerns
- I haven't discovered any new uncovered test/use cases
> Update library to support Node 16

- azure-pipelines.yml
**Description**
Add the npm install step to fix package tests under node6.
The PR was tested via the pipeline. After the changes, the package tests started to work fine on node 6.
> Add additional npm install step to fix package tests under node6

- README.md
- api/TestPlanApi.ts
- api/WebApi.ts
- api/interfaces/TestPlanInterfaces.ts
- package-lock.json
- package.json
- samples/creation.ts
- samples/samples.json
Added testplans API to node sdk : https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps?path=%2FTfs%2FClient%2FTestManagement%2FTestPlanning%2FTestPlanResourceIds.cs&_a=contents&version=GBmaster
This is required to be used in new AzureDevOpsTestPlan task here in repo: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks
> Adding testplan api in node sdk

- README.md
- api/AlertApi.ts
- api/ManagementApi.ts
- api/WebApi.ts
- api/interfaces/AlertInterfaces.ts
- api/interfaces/ManagementInterfaces.ts
- package.json
In this change, we are introducing clients for [GitHub Advanced 
Security for Azure DevOps (GHAzDO)](https://azure.microsoft.com/en-us/products/devops/github-advanced-security).
Summary of the change is as follows:
* Add `api/AlertApi.ts` and `api/ManagementApi.ts` and their
respective interfaces to `api/interfaces`.
* Update `README.md`
* Update `api/WebApi.ts` to integrate the Advanced Security clients.
* Update package version to `12.2.0`.
> Add Advanced Security Node.js clients

- api/AlertApi.ts
- api/ManagementApi.ts
- api/interfaces/AlertInterfaces.ts
- package.json
We are updating the Advanced Security API clients to make a recent change to the `GET /sarifs` endpoint available for consumption.
> Update Advanced Security API clients

- api/AlertApi.ts
- api/CIXApi.ts
- api/GitApi.ts
- api/ManagementApi.ts
- api/PipelinesApi.ts
- api/ReleaseApi.ts
- api/TaskAgentApiBase.ts
- api/TestResultsApi.ts
- api/WebApi.ts
- api/interfaces/AlertInterfaces.ts
- api/interfaces/CIXInterfaces.ts
- api/interfaces/DashboardInterfaces.ts
- api/interfaces/GalleryInterfaces.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/ManagementInterfaces.ts
- api/interfaces/PipelinesInterfaces.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/common/OperationsInterfaces.ts
- api/interfaces/common/VSSInterfaces.ts
- package-lock.json
- package.json
- samples/pipelines.ts
- samples/samples.json
- samples/tsconfig.json
**Description**:
-- Regenerated API for M236
-- Added new Pipelines API endpoints
-- Added samples for the pipelines API
**Testing**
New changes were tested on local org + added pipelines sample
> [Azure DevOps Node API] Add support of the pipelines API

- README.md
- azure-pipelines.yml
- package-lock.json
- package.json
- samples/package-lock.json
- samples/package.json
- test/package-lock.json
**Description**:
- Fixed CVEs in azure-devops-node-api
- Bumped typed-rest-client to v2
- Changed ci tests for node16+
- Modified README file
**Testing**: tested locally
**Related WI**: [AB#2180246](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2180246)
> Fix vulnerable packages

- package-lock.json
- package.json
- samples/package-lock.json
- test/package-lock.json
In this PR I bumped the typed-rest-client version to fix vulnerability issue with the qs package
Please check related PR: https://github.com/microsoft/typed-rest-client/pull/371
https://nvd.nist.gov/vuln/detail/CVE-2022-24999
> Bump typed-rest-client to fix vulnerability issue with the qs package

- api/interfaces/common/VsoBaseInterfaces.ts
- package-lock.json
- package.json
**Description**:
The PR mirroring [IRequestOptions ](https://github.com/microsoft/typed-rest-client/blob/master/lib/Interfaces.ts#L44)from typed-rest-client.
This is needed, because VsoBaseInterfaces.IRequestOptions uses with [WebApi](https://github.com/microsoft/azure-devops-node-api/blob/master/api/WebApi.ts#L169) and [ClientApiBases](https://github.com/microsoft/azure-devops-node-api/blob/master/api/ClientApiBases.ts#L23) which is, basically, wrappers for typed-rest-client's [HttpClient](https://github.com/microsoft/typed-rest-client/blob/master/lib/HttpClient.ts#L125) and [RestClient](https://github.com/microsoft/typed-rest-client/blob/master/lib/RestClient.ts#L43).
_Also, this is potential fix for the problem with 5sec timeout._
Since node19 …
> Mirror typed-rest-client options

- api/interfaces/common/VsoBaseInterfaces.ts
- package-lock.json
- package.json
**WI**
[AB#2217825](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2217825)
**Description**
Include new `globalAgentOptions` property in `IRequestOptions` which was introduced to `typed-rest-client` in this PR: https://github.com/microsoft/typed-rest-client/pull/378
> Add `globalAgentOptions` property to `IRequestOptions` to mirror `typed-rest-client`

- .github/CODEOWNERS
This repo is owned by Tasks & Agent team, it's not related with platform team at all and there are no commits from the platform team.
> remove pipelines platform as codeowner

- azure-pipelines.yml
**Description:** Add the CI step for publishing a prerelease version of the package that can be manually invoked when needed.
**Related WI:** [AB#2278468](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2278468)
> Add the prerelease publishing step in the CI

- azure-pipelines.yml
**Description**: The publishing step is triggered for every strategy item, so we need to check the variable npmVersion to be 8 to publish it only for Nodejs v16
**Related WI**: [AB#2279742](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2279742)
> Publish the package for the Node16 only in CI

- api/VsoClient.ts
- package.json
- test/units/tests.ts
In this change, a bug in the way `VsoClient.queryParamsToStringHelper`
handles array-typed query parameters values is fix. After this change,
a query parameter dictionary like `{states: ["active", "inactive"]}` 
will produce `states=active,inactive` instead of
`states.0=active&states.1=inactive`.
Fix #643
> Fix array-type query parameter handling
