- gulpfile.js
- src/api/BuildApi.ts
- src/api/ClientApiBases.ts
- src/api/CoreApi.ts
- src/api/FileContainerApi.ts
- src/api/GitApi.ts
- src/api/TaskAgentApi.ts
- src/api/TaskApi.ts
- src/api/TestApi.ts
- src/api/TfvcApi.ts
- src/api/WebApi.ts
- src/api/WorkItemTrackingApi.ts
- src/api/handlers/apiversion.ts
- src/api/handlers/basiccreds.ts
- src/api/handlers/bearertoken.ts
- src/api/interfaces/common/VsoBaseInterfaces.ts
- src/test/test.ts
- Created base classes for the different APIs in src/api/ClientApiBases.ts
- Created a factory in src/api/WebApi.ts where user can call methods to instantiate different objects for different Apis
- Copied handlers (auth, creds, tokens) to src/api/handlers from xplat agent.
- Adjusted generated clients to work with structure changes, tested Build, Task, TaskAgent with xplat agent.
> webapi factory + base classes for client APIs

- api/BuildApi.ts
- api/CoreApi.ts
- api/FileContainerApi.ts
- api/GitApi.ts
- api/TaskAgentApi.ts
- api/TaskApi.ts
- api/TestApi.ts
- api/TfvcApi.ts
- api/WorkItemTrackingApi.ts
Operations were silently failing because I did not include this in the generator before...
> added .fail() clause to every operation

- api/BuildApi.ts
- api/CoreApi.ts
- api/FileContainerApi.ts
- api/GitApi.ts
- api/RestClient.ts
- api/TaskAgentApi.ts
- api/TaskApi.ts
- api/TestApi.ts
- api/TfvcApi.ts
- api/WorkItemTrackingApi.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/TfvcInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- api/interfaces/common/SystemDataInterfaces.ts
- api/interfaces/common/VsoBaseInterfaces.ts
- package.json
- removed unnecessary content: string param and updated after pull from VSO
> update august 6 + removed unecessary param in uploads

- api/GalleryApi.ts
- api/WebApi.ts
- api/interfaces/GalleryInterfaces.ts
- package.json
in order to add vs extensions exec commands to tfs-cli
> add Gallery api

- api/BuildApi.ts
- api/CoreApi.ts
- api/FileContainerApi.ts
- api/GalleryApi.ts
- api/GitApi.ts
- api/ReleaseManagementApi.ts
- api/TaskAgentApiBase.ts
- api/TaskApi.ts
- api/TestApi.ts
- api/TfvcApi.ts
- api/WorkItemTrackingApi.ts
- api/interfaces/BuildInterfaces.ts
- api/interfaces/CoreInterfaces.ts
- api/interfaces/GalleryInterfaces.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/ReleaseManagementInterfaces.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/TfvcInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- package.json
Clients are all updated, but have not been tested. The package.json version is updated to 0.6.0.
> Update node clients.

- api/VsoClient.ts
Also added encodeUriComponent() calls for queryValues
> Adding serialization of objects in query string

- api/BuildApi.ts
- api/CoreApi.ts
- api/FileContainerApi.ts
- api/FileContainerApiBase.ts
- api/GalleryApi.ts
- api/GitApi.ts
- api/ReleaseApi.ts
- api/TaskAgentApiBase.ts
- api/TaskApi.ts
- api/TestApi.ts
- api/TfvcApi.ts
- api/WorkItemTrackingApi.ts
- api/interfaces/BuildInterfaces.ts
- api/interfaces/CoreInterfaces.ts
- api/interfaces/FileContainerInterfaces.ts
- api/interfaces/GalleryInterfaces.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/ReleaseInterfaces.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/TfvcInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- package.json
+ file container upload chunking
> update to 3.0

- api/HttpClient.ts
- node/tunnel.d.ts
- package.json
> Add HTTPS request proxy support

- api/GitApi.ts
- api/interfaces/GitInterfaces.ts
- package.json
A lot of new functionality was added to the Git APIs, mostly to support pull requests. We want to use these APIs from TFS build tasks to automatically push comments to PR from a build. 
I have regenerated the APIs from the master branch of mseng.
> Update the Git APIs

- api/WebApi.ts
- api/WorkItemTrackingProcessApi.ts
- api/WorkItemTrackingProcessDefinitionsApi.ts
- api/interfaces/WorkItemTrackingProcessDefinitionsInterfaces.ts
- api/interfaces/WorkItemTrackingProcessInterfaces.ts
- samples/creation.ts
Exposed these APIs, as they are also available on docs.microsoft.com:
Added WorkItemTrackingProcessApi, WorkItemTrackingProcessDefinitionsApi, WorkItemTrackingProcessInterfaces and WorkItemTrackingProcessDefinitionsInterfaces, and made corresponding changes to WebApi.
> Added WorkItemTrackingProcess and WorkItemTrackingProcessDefinitions APIs

- README.md
- api/WebApi.ts
- api/WikiApi.ts
- api/interfaces/WikiInterfaces.ts
- package.json
- samples/creation.ts
> Adding Wiki NodeJs APIs

- api/VsoClient.ts
- package-lock.json
- package.json
Change was originally done by @stevek-axo [here](https://github.com/Microsoft/vsts-node-api/pull/143).
Had some issues running on his fork so did PR directly to master. Thanks for the contribution!
> Fix swallowed promises

- samples/buildArtifact.ts
- samples/samples.json
- samples/tsconfig.json
* List build artifacts
* Download a zip of an artifact
> Add build artifact sample.

- api/opensource/node-http-ntlm/readme.txt
- samples/build.ts
- samples/buildArtifact.ts
- samples/common.ts
- samples/creation.ts
- samples/filecontainer.ts
- samples/package-lock.json
- samples/package.json
- samples/task.ts
@bryanmacfarlane FYI. This fixes all the samples.
I am going to merge now to unblock @damccorm and myself.
> Fix broken sames from lib rename.

- api/VsoClient.ts
- package.json
Fixes issue where key would appear twice in serialized string (e.g. key=key=value instead of key=value).
Addresses #215
> Fixed issue with serialization

- samples/policy.ts
- samples/run.ts
- samples/samples.json
- samples/tsconfig.json
Part of continuing effort to add samples
> Added policy sample

- README.md
> Updated README to add TFS info

- api/VsoClient.ts
> Don't cache failures in BeginGetAreaLocation

- api/WebApi.ts
> Read package.json from package directory

- make.js
- samples/run.ts
Fixes issue where you couldn't run an individual sample.
> Fix individual sample execution

- samples/build.ts
Per #286 we were never actually using these, looks like its been that way since the were added so I'm just getting rid of them
> Get rid of unused objects

- package-lock.json
- package.json
See https://github.com/DiegoRBaquero/node-os for more details
> Remove package os because it is just a re-export of node's core os

- package-lock.json
- package.json
There are basically no significant breaking changes and 3.1.5 is stable. Enables some new features for future development.
Samples run fine with this update FYI.
> Update typescript to v3.1.5

- samples/workItemTracking.ts
> Fix samples

- api/interfaces/common/VsoBaseInterfaces.ts
> Add more requestOptions for typed-rest-client

- api/WebApi.ts
- package-lock.json
- package.json
> Enable webpack

- api/WebApi.ts
- package-lock.json
- package.json
- test/package-lock.json
- test/units/tests.ts
Fixes #321, see discussion there for context
> Revert #313

- api/Serialization.ts
https://github.com/microsoft/azure-devops-node-api/issues/339
> Serialization Fix for Dictionaries With Key as EnumType

- CONTRIBUTING.md
- package-lock.json
- package.json
- test/package-lock.json
- test/units/tests.ts
There are several issues fixed since 1.2.0 release incl. some proxy and no_proxy handling issues
> update typed-rest-client to 1.7.2

- azure-pipelines.yml
This was clearly copied from the task-lib (oops)
> Remove bad working directory

- .github/workflows/autoAssignABTT.yml
Passed token to add labels step.
> Auto assign action - passed token to add labels step

- .github/workflows/autoAssignABTT.yml
Fixed area label name for auto assign action
> Fixed label name - auto assign action

- README.md
Update info about the url structure for ProfileApi (according to the [comment](https://github.com/microsoft/azure-devops-node-api/blob/ff820b2dd0c9a09cf09e64e94d3f95818a77249d/samples/profile.ts#L9))
> Add info about ProfileApi

- azure-pipelines.yml
- make.js
- test/units/tests.ts
Add node versions 6, 10 and 14 to the unit tests, change install directory for tests on node 6, add different expectedString for node 6
> Add node versions 6, 10 and 14 to the unit tests

- azure-pipelines.yml
Ubuntu16 is now deprecated. Use ubuntu-18.04
> Specify ubuntu-18.04 vmImage for CI

- api/BuildApi.ts
- api/FileContainerApiBase.ts
- api/GalleryApi.ts
- api/GitApi.ts
- api/PolicyApi.ts
- api/TaskAgentApiBase.ts
- api/TaskApi.ts
- api/WorkItemTrackingProcessApi.ts
- api/WorkItemTrackingProcessDefinitionsApi.ts
- api/interfaces/BuildInterfaces.ts
- api/interfaces/ExtensionManagementInterfaces.ts
- api/interfaces/GalleryInterfaces.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/GraphInterfaces.ts
- api/interfaces/NotificationInterfaces.ts
- api/interfaces/ReleaseInterfaces.ts
- api/interfaces/SBOMInterfaces.ts
- api/interfaces/ServiceEndpointInterfaces.ts
- api/interfaces/TaskAgentInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/TfvcInterfaces.ts
- api/interfaces/WorkInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- api/interfaces/WorkItemTrackingProcessInterfaces.ts
- api/interfaces/common/VSSInterfaces.ts
- package-lock.json
- package.json
- samples/package-lock.json
- test/package-lock.json
Generated from M216 release of ADO
> M216 API updates

- api/AlertApi.ts
- api/ExtensionManagementApi.ts
- api/FileContainerApiBase.ts
- api/GalleryApi.ts
- api/GitApi.ts
- api/ManagementApi.ts
- api/ReleaseApi.ts
- api/TestResultsApi.ts
- api/interfaces/AlertInterfaces.ts
- api/interfaces/BuildInterfaces.ts
- api/interfaces/CommentsInterfaces.ts
- api/interfaces/CoreInterfaces.ts
- api/interfaces/DashboardInterfaces.ts
- api/interfaces/DeploymentInterfaces.ts
- api/interfaces/GalleryInterfaces.ts
- api/interfaces/GitInterfaces.ts
- api/interfaces/NotificationInterfaces.ts
- api/interfaces/ReleaseInterfaces.ts
- api/interfaces/SBOMInterfaces.ts
- api/interfaces/TestInterfaces.ts
- api/interfaces/TestPlanInterfaces.ts
- api/interfaces/WorkItemTrackingInterfaces.ts
- api/interfaces/WorkItemTrackingProcessDefinitionsInterfaces.ts
- api/interfaces/WorkItemTrackingProcessInterfaces.ts
- package-lock.json
- package.json
***Description:*** This PR contains updates generated from the `releases/M234` AzureDevOps branch. It includes only modified files. No deleted or untracked files are included. Also, incorrect imports are fixed manually.
> M234 API updates

- azure-pipelines.yml
- Move publishing to npm task
- Migrate the pipeline to another pool and org
> 1ES Migration

- azure-pipelines.yml
**Description:** This PR adds the customEndpoint property to Npm tasks, allowing the authorized interaction with Npmjs registry through the service connection. 
**Related WI:** [AB#2279776](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2279776)
> Add the customEndpoint property to Npm tasks

- azure-pipelines.yml
**Description:** This PR adds the build task to the stage Release latest as we based the getting of the package version and name on _build folder
> Add the building task to the stage Relase latest
